# Generated by Django 5.1.6 on 2025-02-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='mage',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
    ]
